cabal-version:      3.8
name:               andamio-blueprints
maintainer:         andamio.io
version:            0.1.0.0
build-type:         Simple
synopsis:           A Haskell project to write all blueprints to blueprints/
data-dir:           blueprints/
data-files:         index.plutus

source-repository head
  type:     git
  location: https://github.com/Andamio-Platform/access-token

executable write-blueprints
   default-language:    Haskell2010

   ghc-options:         -Wall 
                       -fobject-code 
                       -fno-ignore-interface-pragmas 
                       -fno-omit-interface-pragmas 
                       -fno-strictness 
                       -fno-spec-constr 
                       -fno-specialise
                       -fno-full-laziness
                       -fno-unbox-strict-fields
                       -fno-unbox-small-strict-fields
                       -fno-show-valid-hole-fits

   hs-source-dirs: app
   main-is: write-blueprints.hs
   other-modules: Paths_andamio_blueprints
   ghc-options: -O2 -threaded -rtsopts -with-rtsopts=-T
   build-depends:
       , base
       , plutus-tx
       , andamio-access-token
       , filepath